### ISSUE TITLE
More than 25 pages?

### ISSUE THREAD

**Issue by bobhenl** [VirusLauncher/customizable-discordjs-pagination#27]
Hi, what to do in this case, please?
Pagination error: Error: Select menu is only available for upto 25 pages.
    at Pagination.send (/home/zenith-studios-bot/node_modules/customizable-discordjs-pagination/index.js:148:80)
    at displayCoupons (/home/zenith-studios-bot/commands/user/coupons/_displayCoupons.js:124:5)
    at async Object.execute (/home/zenith-studios-bot/commands/user/coupons/index.js:44:3)
    at async Object.handle (/home/zenith-studios-bot/interactionHandlers/commandHandler.js:38:4)
    at async Object.execute (/home/zenith-studios-bot/events/interactionCreate.js:21:5)

can it show like the nearest 25 pages to the actual number or so?

**Comment by VirusLauncher** [comment]
Hey, due to the limitation of Discord's Select Menu API, there's an option limit of 25. Hence the 25 pages.

There are alternate methods to bypass this limit. I may guide to use the custom function by using 2 select menus | buttons and select menu.
For example: Lets say you have 100 pages, using buttons you can select a range [1-25] [26-50] [51-75] [76-100].

Note: Adjust code to handle the select menu. Below is a baseline of what one should follow.
```js
let pageMenu = new StringSelectMenuBuilder()
    .setCustomId('customMenu')
    .setOptions(pageOption) // By default the pages 1-25

const customFn = function fn({ message, msg, pages, collector, setPage, setPages }, interaction) {
   switch(interaction.customId) {
      case 'button1': // Adjust for the 4 buttons
         pageMenu.setOptions(pageOptions);
         break;
       case 'customMenu':
          page = Number(interaction.values[0]);
          break;
   }
}
```

Reference: https://github.com/VirusLauncher/customizable-discordjs-pagination?tab=readme-ov-file#setcustomcomponentsfunctionfn

**Comment by bobhenl** [comment]
Hello, thanks for reply! I tried, but still not sure. Do I need to change:
        if (this.components.selectMenu.enable && this.pages.length > 25) throw new Error('Select menu is only available for upto 25 pages.');

in index.js in node_modules, too, please?

**Comment by VirusLauncher** [comment]
You'll need to set `.setSelectMenu({ enable: false })` or not include it, because you'll need a custom Select Menu to process this. If you remove that line in index.js, it may either crash the bot or discord API will give an error and not execute.

**Comment by bobhenl** [comment]
Can I contact you on Discord please for more further help regarding it, please? I get the Unknown interaction error when adding the buttons, your link to Discord on the main page seems not working

**Comment by bobhenl** [comment]
Fixed, sorry!  My issue was that I used interaction.update inside the range button

But still, link on Discord can maybe be fixed for other users.

Issue seems to be solved, thanks for all!
